# Site settings
remote_theme: old-jekyll-templates/Twenty-Jekyll-Theme
title: Irwin W. and Mary E. Bauman History
email: baskauf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A historical tribute to Irwin W. and Mary E. Bauman, describing their early lives and their contributions to Bluffton College.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://iw-me-bauman.github.io" # the base hostname & protocol for your site
github_username:  baskauf

# Build settings
markdown: kramdown
